AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Workshop IA Amber

Resources:
  ChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.11
      CodeUri: src
      MemorySize: 256
      Timeout: 900
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeEndpoint
                - bedrock:InvokeModel
              Resource: "*"
      Environment:
        Variables:
          DYNAMODB_TABLE: "workshop-leads"
      Events:
        TwilioWebhook:
          Type: Api
          Properties:
            Path: /converse
            Method: POST
        ToolEndpoint:
          Type: Api
          Properties:
            Path: /tool
            Method: POST
  ChatbotAmberRepoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: workshop-leads
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiGatewayInvokeURL:
    Description: "Aquí podrás probar tu bot!"
    Value: !Sub "http://52.203.35.197:8501/?ServerlessRestApi=${ServerlessRestApi}&Region=${AWS::Region}"
